apiVersion: v1
kind: Service
metadata:
  name: feedback-frontend-service
spec:
  selector:
    app: feedback-frontend
  ports:
    - protocol: TCP
      port: 80  # Der Port, den der Service bereitstellt
      targetPort: 80  # Der Port, auf dem der Container lauscht
  type: LoadBalancer  # Verwende ClusterIP, NodePort oder LoadBalancer je nach Bedarf
